version: "3.4"

services:
  harpia-angular:
    build:
      context: .
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
    image: harpia-angular
    container_name: harpia-angular
    ports:
      - 81:80
    networks:
      - network
networks:
  network:
    driver: bridge
