# Define o bloco do servidor que vai hospedar a aplicação
server {
  # O Nginx vai escutar na porta 80, que é a porta padrão para HTTP
  listen 80;

  # Define o diretório raiz onde os arquivos do site estão localizados.
  # Corresponde ao destino da cópia no seu Dockerfile.
  root /usr/share/nginx/html;

  # Define o arquivo de índice padrão
  index index.html index.htm;

  # Bloco de localização para todas as requisições (/)
  location / {
    # Tenta servir o arquivo solicitado diretamente ($uri),
    # ou como um diretório ($uri/),
    # e se não encontrar, redireciona para o index.html.
    # Isso é essencial para que o roteamento do Angular (client-side) funcione.
    try_files $uri $uri/ /index.html;
  }
}
