name: Deploy Front-end Angular com Docker

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH local
        run: |
          mkdir -p ~/.ssh
          chmod 600 /home/tivic/.ssh/github_runner_key
          ln -sf /home/tivic/.ssh/github_runner_key ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.159 >> ~/.ssh/known_hosts


      - name: Copiar projeto para servidor remoto
        run: |
          ssh -i ~/.ssh/github_runner_key tivic@192.168.1.159 'rm -rf /home/tivic/front-app && mkdir -p /home/tivic/front-app'
          scp -i ~/.ssh/github_runner_key -r $GITHUB_WORKSPACE/* tivic@192.168.1.159:/home/tivic/front-app

      - name: Subir aplicação via Docker Compose
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          ssh -i ~/.ssh/github_runner_key tivic@192.168.1.159 << EOF
            export NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN
            cd /home/tivic/front-app
            docker-compose build --build-arg NPM_AUTH_TOKEN=\$NPM_AUTH_TOKEN
            docker-compose up -d
          EOF


